//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class academic_levels
    {
        public academic_levels()
        {
            this.groups = new HashSet<groups>();
            this.subjects = new HashSet<subjects>();
        }
    
        public int academic_level_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
        public virtual ICollection<subjects> subjects { get; set; }
    }
}
