//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_messages
    {
        public int message_id { get; set; }
        public int user_id { get; set; }
        public string text { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
