//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using TheLazyServer;

public partial class the_lazyEntities1 : DbContext
{
    public the_lazyEntities1()
        : base("name=the_lazyEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<academic_levels> academic_levels { get; set; }
    public DbSet<chat_messages> chat_messages { get; set; }
    public DbSet<chat_rooms> chat_rooms { get; set; }
    public DbSet<education_centers> education_centers { get; set; }
    public DbSet<element_comments> element_comments { get; set; }
    public DbSet<elements> elements { get; set; }
    public DbSet<groups> groups { get; set; }
    public DbSet<likes> likes { get; set; }
    public DbSet<notifications> notifications { get; set; }
    public DbSet<posts> posts { get; set; }
    public DbSet<purchases> purchases { get; set; }
    public DbSet<reports> reports { get; set; }
    public DbSet<sessions> sessions { get; set; }
    public DbSet<subjects> subjects { get; set; }
    public DbSet<users> users { get; set; }
}
