//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class education_centers
    {
        public education_centers()
        {
            this.groups = new HashSet<groups>();
        }
    
        public int education_center_id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
    }
}
