//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class elements
    {
        public elements()
        {
            this.element_comments = new HashSet<element_comments>();
            this.likes = new HashSet<likes>();
            this.purchases = new HashSet<purchases>();
            this.reports = new HashSet<reports>();
        }
    
        public int element_id { get; set; }
        public int user_id { get; set; }
        public int subject_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual ICollection<element_comments> element_comments { get; set; }
        public virtual ICollection<likes> likes { get; set; }
        public virtual ICollection<purchases> purchases { get; set; }
        public virtual ICollection<reports> reports { get; set; }
        public virtual subjects subjects { get; set; }
        public virtual users users { get; set; }
    }
}
