//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.users = new HashSet<users>();
        }
    
        public int group_id { get; set; }
        public string group_code { get; set; }
        public int academic_level_id { get; set; }
        public int education_center_id { get; set; }
    
        public virtual academic_levels academic_levels { get; set; }
        public virtual education_centers education_centers { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
