//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public posts()
        {
            this.reports = new HashSet<reports>();
        }
    
        public int post_id { get; set; }
        public Nullable<int> parent_post_id { get; set; }
        public int user_id { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
    
        public virtual ICollection<reports> reports { get; set; }
        public virtual users users { get; set; }
    }
}
