//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions
    {
        public int session_id { get; set; }
        public int user_id { get; set; }
        public string ipendpoint { get; set; }
        public int status { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
    
        public virtual users users { get; set; }
    }
}
