//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLazyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        public subjects()
        {
            this.elements = new HashSet<elements>();
        }
    
        public int subject_id { get; set; }
        public string name { get; set; }
        public int academic_level_id { get; set; }
    
        public virtual academic_levels academic_levels { get; set; }
        public virtual ICollection<elements> elements { get; set; }
    }
}
